services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      BACKEND_GRAPHQL_URL: ${BACKEND_GRAPHQL_URL:-http://localhost:4200/graphql}
    restart: unless-stopped
