import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { cookies } from 'next/headers'

import { MainProvider } from '@/providers/MainProvider'

import '../globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

async function getUserProfile() {
	const cookieStore = await cookies()
	const cookiesHeader = cookieStore.toString()

	const res = await fetch('http://localhost:3000/api/graphql', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
			cookie: cookiesHeader
		},
		body: JSON.stringify({
			operationName: 'profile',
			query: `
        query Profile {
          profile {
            name
            surname
            email
            birthDate
            phone
            country
            region
            city
            address
          }
        }
      `
		}),
		cache: 'no-store'
	})

	if (!res.ok) return null

	const json = await res.json()
	return json?.data?.profile ?? null
}

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const user = await getUserProfile()

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<MainProvider user={user}>{children}</MainProvider>
			</body>
		</html>
	)
}
